<!-- about-us -->
 <div id="about" class="about">
     <div class="container">
         <div class="col-md-7 about-left">
             <h3>Nós somos a RRCA!</h3>
             <div class="strip"></div>
             <h2>Empresa de desenvolvimento de softwares para Negócios Digitais.</h2>
             <p>A RRCA é uma empresa fictícia criada para o trabalho da disciplina Aplicação da Engenharia Software do
                 curso de Ciência da Computação da UNISUL (Universidade do Sul de Santa Catarina).</p>
         </div>
         <div class="col-md-5 about-right text-center">
             <img src="<?php echo $this->baseUrl("images/5.png"); ?>" alt="" />
         </div>
         <div class="clearfix"></div>
     </div>
 </div>
 <!-- //about-us -->
 <!-- what-we-do -->
 <div id="what-we-do" class="what-we-do">
     <div class="container">
         <div class="what-info">
             <h3>O que fazemos</h3>
             <div class="strip"></div>
             <p>Nós desenvolvemos sistemas web para vários ramos de negócios digitais e nunca paramos de aprender. Isso é o que nós fazemos..</p>
         </div>
         <div class="what-grids">
             <div class="col-md-3 what-grid text-center">
                 <div class="hand-icon"></div>
                 <h3>PROJETO ORIGINAL</h3>
                 <div class="border"></div>
             </div>
             <div class="col-md-3 what-grid text-center">
                 <div class="headset-icon"></div>
                 <h3>SUPORTE TÉCNICO</h3>
                 <div class="border"></div>
             </div>
             <div class="col-md-3 what-grid text-center">
                 <div class="star-icon"></div>
                 <h3>SOLUÇÃO CRIATIVA</h3>
                 <div class="border"></div>
             </div>
             <div class="col-md-3 what-grid text-center">
                 <div class="box-icon"></div>
                 <h3>IDÉIA DIFERENCIADA</h3>
                 <div class="border"></div>
             </div>
             <div class="clearfix"></div>
         </div>
     </div>
 </div>
 <!-- //what-we-do -->
 <!-- contact -->
 <div id="contact" class="contact">
     <div class="container">
         <div class="contact-info">
             <h3>Contato</h3>
             <div class="strip"></div>
         </div>
         <div class="contact-form">
             <form>
                 <div class="contact-left">
                     <input type="text" placeholder="Nome" required>
                     <input type="text" placeholder="E-mail" required>
                     <input type="text" placeholder="Assunto" required>
                 </div>
                 <div class="contact-right">
                     <textarea placeholder="Mensagem" required></textarea>
                 </div>
                 <div class="clearfix"></div>
                 <input type="submit" value="ENVIAR">
             </form>
         </div>
     </div>
 </div>
 <!-- //contact -->