<!-- DATA TABLES -->
<link href="<?php echo $this->baseUrl("plugins/datatables/dataTables.bootstrap.css"); ?>" rel="stylesheet" type="text/css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Post
        <small>novo post</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="<?php echo $this->baseUrl("/admin"); ?>"><i class="fa fa-dashboard"></i> Início</a></li>
        <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'post'), null, 1); ?>">Posts</a></li>
        <li class="active">novo</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Novo Post</h3>
            </div><!-- /.box-header -->
            <?php if (!isset($this->error)): ?>
            <div class="clearfix"></div>
            <!-- form start -->
            <form role="form" action="" method="post">
              <div class="box-body">
                <div class="form-group">
                  <?php echo $this->form->titulo; ?>
                </div>
                <div class="form-group">
                  <?php echo $this->form->conteudo; ?>
                </div>
              </div><!-- /.box-body -->

              <div class="box-footer">
                <?php echo $this->form->submit; ?>
              </div>
            </form>
            <?php endif; ?>
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div>   <!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- jQuery 2.1.3 -->
<script src="<?php echo $this->baseUrl("plugins/jQuery/jQuery-2.1.3.min.js"); ?>" ></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="<?php echo $this->baseUrl("bootstrap/js/bootstrap.min.js"); ?>" type="text/javascript"></script>
<!-- SlimScroll -->
<script src="<?php echo $this->baseUrl("plugins/slimScroll/jquery.slimscroll.min.js"); ?>" type="text/javascript"></script>
<!-- FastClick -->
<script src="<?php echo $this->baseUrl("plugins/fastclick/fastclick.min.js"); ?>" ></script>
<!-- AdminLTE App -->
<script src="<?php echo $this->baseUrl("dist/js/app.min.js"); ?>" type="text/javascript"></script>
<!-- CK Editor -->
<script src="<?php echo $this->baseUrl("plugins/ckeditor/ckeditor.js"); ?>" ></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="<?php echo $this->baseUrl("plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"); ?>" type="text/javascript"></script>
<script type="text/javascript">
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('conteudo');
    //bootstrap WYSIHTML5 - text editor
    $(".textarea").wysihtml5();
  });
</script>