<div class="login-box-body">
  <?php if($this->error): ?>
  <div class='notification'>
      <p class="login-box-msg"><?php echo $this->error; ?></p>
  </div>
  <?php endif; ?>

  <form action="" method="post">
    <div class="form-group has-feedback">
      <?php echo $this->form->email; ?>
      <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
      <?php echo $this->form->senha; ?>
      <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <?php echo $this->form->submit; ?>
      </div><!-- /.col -->
    </div>
  </form>
  <a href="">Esqueci minha senha</a><br>
  <a href="" class="text-center">Cadastre-se</a>

</div><!-- /.login-box-body -->