<?php
$modelUsuario = new Application_Model_Usuario();
foreach ($this->posts as $post):
    $data = new DateTime($post['data']);
    $urlPost = $this->baseUrl($post['url_post']);
    $urlRedesSociais = 'http://rrca.esy.es/' . $post['url_post'];
    //$numeroConmentarios = $this->getNumComentario($urlRedesSociais);
?>
    <div class="post">
        <div class="container">
            <div class="conteudo">
                <h4><?php echo $data->format('d/m/Y H:i'); ?></h4>
                <h3><a href="<?php echo $urlPost; ?>"><?php echo $post['titulo']; ?></a></h3>
                <p><strong>Publicado por:</strong> <?php echo $modelUsuario->getNomeUsuario($post['id_usuario']); ?></p>
                <div class="strip"></div>
                <p style="text-align: center;">
                  <a href="<?php echo $urlPost; ?>">
                    <img src="http://rrca.esy.es/images/capa_post/<?php echo $post['imagem_capa']; ?>.jpg" style="height:auto; max-width: 500px;" />
                  </a>
                </p>
                <div class="strip"></div>
                <!-- <div><strong><?php //echo $numeroConmentarios; ?></strong></div> -->
            </div>
            <div class="redes_sociais">
                <div class="fb-like" data-href="<?php echo $urlRedesSociais; ?>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false" ></div>
                <div class="fb-share-button" data-href="<?php echo $urlRedesSociais; ?>" data-type="button" ></div>
            </div>
            <a href="<?php echo $urlPost; ?>" class="hvr-sweep-to-right button">LEIA MAIS</a>
        </div>
    </div>
<?php endforeach; ?>
<?php echo $this->paginationControl($this->posts, 'Sliding', 'pagination.phtml'); ?>